name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Install dependencies
        run: sudo apt install -y make wget llvm clang gcc git npm gulp libbpf-dev
      - name: Build with make
        run: make
      - name: Test with the Go CLI
        run: sudo go test -v ./...